ARG NODE_VERSION=22-alpine
FROM node:${NODE_VERSION} AS node

FROM php:8.2-apache AS php
WORKDIR /var/www/html
ARG UID
ARG GID

RUN apt-get update && \
    apt-get install -y \
    curl sudo git gh

# Add extensions not included in the base image
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/download/2.7.24/install-php-extensions /usr/local/bin/
RUN install-php-extensions gd gmp pdo_pgsql zip
COPY docker/sites-available/000-default.conf.dev /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite headers

RUN addgroup --gid $GID laravel && \
    adduser --uid $UID --gid $GID --disabled-password --gecos "" laravel && \
    echo 'laravel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN chown -R laravel:laravel .
USER laravel

ENV NVM_DIR /home/laravel/.nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install 22