FROM ubuntu:22.04
RUN apt update
RUN apt install -y locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8
RUN apt install -y hunspell hunspell-hu netcat-openbsd
RUN mkdir -p /var/run/hunspell
RUN mkfifo /var/run/hunspell/pipe

ENTRYPOINT [ "/usr/bin/hunspell", "-m", "-i", "utf-8", "-d", "hu_HU"]
