ARG NODE_VERSION=22-alpine
FROM node:${NODE_VERSION} AS node

FROM php:8.2-apache AS php
WORKDIR /var/www/html
ARG UID
ARG GID

# Hunspell doesn't work without a proper locale :o
RUN apt-get update && \
    apt-get install -y \
    curl sudo git gh nano hunspell hunspell-hu locales python3 jq
RUN sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
RUN sed -i 's/^# *\(hu_HU.UTF-8\)/\1/' /etc/locale.gen

RUN locale-gen en_US.UTF-8 hu_HU.UTF-8

# Add extensions not included in the base image
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN install-php-extensions gd gmp memcached pdo_pgsql pdo_mysql xdebug zip pcntl imagick exif intl
COPY docker/sites-available/000-default.conf.dev /etc/apache2/sites-available/000-default.conf

RUN echo "xdebug.mode=debug,develop" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.log=/tmp/xdebug.log" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# The Greek import parses a ~44MB source CSV into memory; the default 128M is not enough.
RUN echo "memory_limit=1G" > /usr/local/etc/php/conf.d/docker-php-memory.ini

RUN a2enmod rewrite headers

RUN addgroup --gid $GID laravel && \
    adduser --uid $UID --gid $GID --disabled-password --gecos "" laravel && \
    echo 'laravel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN chown -R laravel:laravel .

USER laravel

ENV NVM_DIR /home/laravel/.nvm
ENV PATH "/home/laravel/.local/bin:${PATH}"

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install 22 \
    && nvm use 22 \
    && curl -fsSL https://claude.ai/install.sh | bash

